#############################################################################
# Makefile for building: Project
# Generated by qmake (3.1) (Qt 5.9.2)
# Project:  Project.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Project.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2  -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2  -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/QtWidgets -isystem /usr/include/QtGui -isystem /usr/include/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib64/qt5/mkspecs/linux-g++ -Isrc/SQLITE
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Project1.0.0
DISTDIR = /home/andris/Documents/egyetem/design_patterns/Project/.tmp/Project1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread -lsqlite3
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qrc_application.cpp \
		src/BUSINESS/Administrator.cpp \
		src/BUSINESS/DeadlineLister.cpp \
		src/BUSINESS/ElementDropper.cpp \
		src/BUSINESS/ElementLister.cpp \
		src/BUSINESS/TaskLister.cpp \
		src/BUSINESS/TaskSwitcher.cpp \
		src/DAO/DAOEmployee.cpp \
		src/DAO/DAOFactory.cpp \
		src/DAO/DAOInterface.cpp \
		src/DAO/DAOProject.cpp \
		src/DAO/DAOTask.cpp \
		src/TEST/QTTest01.cpp \
		src/TRANSFER/Date.cpp \
		src/TRANSFER/Employee.cpp \
		src/TRANSFER/Project.cpp \
		src/TRANSFER/Task.cpp \
		src/UI/ActionHandler.cpp \
		src/UI/CommandAdapter.cpp \
		src/UI/MainWindow.cpp \
		moc_MainWindow.cpp
OBJECTS       = qrc_application.o \
		Administrator.o \
		DeadlineLister.o \
		ElementDropper.o \
		ElementLister.o \
		TaskLister.o \
		TaskSwitcher.o \
		DAOEmployee.o \
		DAOFactory.o \
		DAOInterface.o \
		DAOProject.o \
		DAOTask.o \
		QTTest01.o \
		Date.o \
		Employee.o \
		Project.o \
		Task.o \
		ActionHandler.o \
		CommandAdapter.o \
		MainWindow.o \
		moc_MainWindow.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		Project.pro src/BUSINESS/Administrator.hpp \
		src/BUSINESS/Deadline.hpp \
		src/BUSINESS/DeadlineLister.hpp \
		src/BUSINESS/ElementDropper.hpp \
		src/BUSINESS/ElementFactory.hpp \
		src/BUSINESS/ElementLister.hpp \
		src/BUSINESS/EmployeeFactory.hpp \
		src/BUSINESS/EmployeeLister.hpp \
		src/BUSINESS/ProjectFactory.hpp \
		src/BUSINESS/ProjectOrganizer.hpp \
		src/BUSINESS/TaskFactory.hpp \
		src/BUSINESS/TaskHandler.hpp \
		src/BUSINESS/TaskLister.hpp \
		src/BUSINESS/TaskSwitcher.hpp \
		src/DAO/DAO.hpp \
		src/DAO/DAOEmployee.hpp \
		src/DAO/DAOFactory.hpp \
		src/DAO/DAOInterface.hpp \
		src/DAO/DAOProject.hpp \
		src/DAO/DAOTask.hpp \
		src/DAO/Query.hpp \
		src/LIB/dynamic_array.hpp \
		src/TRANSFER/Date.hpp \
		src/TRANSFER/Employee.hpp \
		src/TRANSFER/Object.hpp \
		src/TRANSFER/Project.hpp \
		src/TRANSFER/Task.hpp \
		src/UI/ActionHandler.hpp \
		src/UI/CommandAdapter.hpp \
		src/UI/DeleteMenuDlg.hpp \
		src/UI/ListMenuDlg.hpp \
		src/UI/MainWindow.h qrc_application.cpp \
		src/BUSINESS/Administrator.cpp \
		src/BUSINESS/DeadlineLister.cpp \
		src/BUSINESS/ElementDropper.cpp \
		src/BUSINESS/ElementLister.cpp \
		src/BUSINESS/TaskLister.cpp \
		src/BUSINESS/TaskSwitcher.cpp \
		src/DAO/DAOEmployee.cpp \
		src/DAO/DAOFactory.cpp \
		src/DAO/DAOInterface.cpp \
		src/DAO/DAOProject.cpp \
		src/DAO/DAOTask.cpp \
		src/TEST/QTTest01.cpp \
		src/TRANSFER/Date.cpp \
		src/TRANSFER/Employee.cpp \
		src/TRANSFER/Project.cpp \
		src/TRANSFER/Task.cpp \
		src/UI/ActionHandler.cpp \
		src/UI/CommandAdapter.cpp \
		src/UI/MainWindow.cpp
QMAKE_TARGET  = Project
DESTDIR       = 
TARGET        = Project


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Project.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		Project.pro \
		application.qrc \
		/usr/lib64/libQt5Widgets.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -o Makefile Project.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/toolchain.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/qmake_use.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
Project.pro:
application.qrc:
/usr/lib64/libQt5Widgets.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Project.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents application.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/BUSINESS/Administrator.hpp src/BUSINESS/Deadline.hpp src/BUSINESS/DeadlineLister.hpp src/BUSINESS/ElementDropper.hpp src/BUSINESS/ElementFactory.hpp src/BUSINESS/ElementLister.hpp src/BUSINESS/EmployeeFactory.hpp src/BUSINESS/EmployeeLister.hpp src/BUSINESS/ProjectFactory.hpp src/BUSINESS/ProjectOrganizer.hpp src/BUSINESS/TaskFactory.hpp src/BUSINESS/TaskHandler.hpp src/BUSINESS/TaskLister.hpp src/BUSINESS/TaskSwitcher.hpp src/DAO/DAO.hpp src/DAO/DAOEmployee.hpp src/DAO/DAOFactory.hpp src/DAO/DAOInterface.hpp src/DAO/DAOProject.hpp src/DAO/DAOTask.hpp src/DAO/Query.hpp src/LIB/dynamic_array.hpp src/TRANSFER/Date.hpp src/TRANSFER/Employee.hpp src/TRANSFER/Object.hpp src/TRANSFER/Project.hpp src/TRANSFER/Task.hpp src/UI/ActionHandler.hpp src/UI/CommandAdapter.hpp src/UI/DeleteMenuDlg.hpp src/UI/ListMenuDlg.hpp src/UI/MainWindow.h $(DISTDIR)/
	$(COPY_FILE) --parents qrc_application.cpp src/BUSINESS/Administrator.cpp src/BUSINESS/DeadlineLister.cpp src/BUSINESS/ElementDropper.cpp src/BUSINESS/ElementLister.cpp src/BUSINESS/TaskLister.cpp src/BUSINESS/TaskSwitcher.cpp src/DAO/DAOEmployee.cpp src/DAO/DAOFactory.cpp src/DAO/DAOInterface.cpp src/DAO/DAOProject.cpp src/DAO/DAOTask.cpp src/TEST/QTTest01.cpp src/TRANSFER/Date.cpp src/TRANSFER/Employee.cpp src/TRANSFER/Project.cpp src/TRANSFER/Task.cpp src/UI/ActionHandler.cpp src/UI/CommandAdapter.cpp src/UI/MainWindow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp
qrc_application.cpp: application.qrc \
		/usr/bin/rcc \
		src/TEST/save.png \
		src/TEST/open.png \
		src/TEST/cut.png \
		src/TEST/copy.png \
		src/TEST/delete.png \
		src/TEST/paste.png
	/usr/bin/rcc -name application application.qrc -o qrc_application.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp
moc_MainWindow.cpp: src/UI/CommandAdapter.hpp \
		src/BUSINESS/Administrator.hpp \
		src/DAO/DAO.hpp \
		src/DAO/DAOFactory.hpp \
		src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp \
		src/DAO/DAOEmployee.hpp \
		src/TRANSFER/Employee.hpp \
		src/DAO/DAOProject.hpp \
		src/TRANSFER/Project.hpp \
		src/DAO/DAOTask.hpp \
		src/TRANSFER/Task.hpp \
		src/BUSINESS/Deadline.hpp \
		src/TRANSFER/Date.hpp \
		src/DAO/DAUtils.cpp \
		src/BUSINESS/ElementFactory.hpp \
		src/BUSINESS/TaskSwitcher.hpp \
		src/BUSINESS/ElementDropper.hpp \
		src/BUSINESS/TaskLister.hpp \
		src/BUSINESS/ElementLister.hpp \
		src/BUSINESS/EmployeeLister.hpp \
		src/BUSINESS/EmployeeFactory.hpp \
		src/BUSINESS/TaskFactory.hpp \
		src/BUSINESS/ProjectFactory.hpp \
		src/UI/ActionHandler.hpp \
		src/UI/MainWindow.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/andris/Documents/egyetem/design_patterns/Project -I/home/andris/Documents/egyetem/design_patterns/Project -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtCore -I/usr/include/c++/7.2.0 -I/usr/include/c++/7.2.0/x86_64-solus-linux -I/usr/include/c++/7.2.0/backward -I/usr/lib64/gcc/x86_64-solus-linux/7.2.0/include -I/usr/lib64/gcc/x86_64-solus-linux/7.2.0/include-fixed -I/usr/include src/UI/MainWindow.h -o moc_MainWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_application.o qrc_application.cpp

Administrator.o: src/BUSINESS/Administrator.cpp src/BUSINESS/Administrator.hpp \
		src/DAO/DAO.hpp \
		src/DAO/DAOFactory.hpp \
		src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp \
		src/DAO/DAOEmployee.hpp \
		src/TRANSFER/Employee.hpp \
		src/DAO/DAOProject.hpp \
		src/TRANSFER/Project.hpp \
		src/DAO/DAOTask.hpp \
		src/TRANSFER/Task.hpp \
		src/BUSINESS/Deadline.hpp \
		src/TRANSFER/Date.hpp \
		src/DAO/DAUtils.cpp \
		src/BUSINESS/ElementFactory.hpp \
		src/BUSINESS/TaskSwitcher.hpp \
		src/BUSINESS/ElementDropper.hpp \
		src/BUSINESS/TaskLister.hpp \
		src/BUSINESS/ElementLister.hpp \
		src/BUSINESS/EmployeeLister.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Administrator.o src/BUSINESS/Administrator.cpp

DeadlineLister.o: src/BUSINESS/DeadlineLister.cpp src/BUSINESS/DeadlineLister.hpp \
		src/BUSINESS/ElementLister.hpp \
		src/DAO/DAO.hpp \
		src/DAO/DAOFactory.hpp \
		src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp \
		src/DAO/DAOEmployee.hpp \
		src/TRANSFER/Employee.hpp \
		src/DAO/DAOProject.hpp \
		src/TRANSFER/Project.hpp \
		src/DAO/DAOTask.hpp \
		src/TRANSFER/Task.hpp \
		src/BUSINESS/Deadline.hpp \
		src/TRANSFER/Date.hpp \
		src/DAO/DAUtils.cpp \
		src/BUSINESS/TaskLister.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DeadlineLister.o src/BUSINESS/DeadlineLister.cpp

ElementDropper.o: src/BUSINESS/ElementDropper.cpp src/BUSINESS/ElementDropper.hpp \
		src/DAO/DAO.hpp \
		src/DAO/DAOFactory.hpp \
		src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp \
		src/DAO/DAOEmployee.hpp \
		src/TRANSFER/Employee.hpp \
		src/DAO/DAOProject.hpp \
		src/TRANSFER/Project.hpp \
		src/DAO/DAOTask.hpp \
		src/TRANSFER/Task.hpp \
		src/BUSINESS/Deadline.hpp \
		src/TRANSFER/Date.hpp \
		src/DAO/DAUtils.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ElementDropper.o src/BUSINESS/ElementDropper.cpp

ElementLister.o: src/BUSINESS/ElementLister.cpp src/BUSINESS/ElementLister.hpp \
		src/DAO/DAO.hpp \
		src/DAO/DAOFactory.hpp \
		src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp \
		src/DAO/DAOEmployee.hpp \
		src/TRANSFER/Employee.hpp \
		src/DAO/DAOProject.hpp \
		src/TRANSFER/Project.hpp \
		src/DAO/DAOTask.hpp \
		src/TRANSFER/Task.hpp \
		src/BUSINESS/Deadline.hpp \
		src/TRANSFER/Date.hpp \
		src/DAO/DAUtils.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ElementLister.o src/BUSINESS/ElementLister.cpp

TaskLister.o: src/BUSINESS/TaskLister.cpp src/BUSINESS/TaskLister.hpp \
		src/BUSINESS/ElementLister.hpp \
		src/DAO/DAO.hpp \
		src/DAO/DAOFactory.hpp \
		src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp \
		src/DAO/DAOEmployee.hpp \
		src/TRANSFER/Employee.hpp \
		src/DAO/DAOProject.hpp \
		src/TRANSFER/Project.hpp \
		src/DAO/DAOTask.hpp \
		src/TRANSFER/Task.hpp \
		src/BUSINESS/Deadline.hpp \
		src/TRANSFER/Date.hpp \
		src/DAO/DAUtils.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TaskLister.o src/BUSINESS/TaskLister.cpp

TaskSwitcher.o: src/BUSINESS/TaskSwitcher.cpp src/BUSINESS/TaskSwitcher.hpp \
		src/TRANSFER/Employee.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/DAO.hpp \
		src/DAO/DAOFactory.hpp \
		src/DAO/DAOInterface.hpp \
		src/DAO/Query.hpp \
		src/DAO/DAOEmployee.hpp \
		src/DAO/DAOProject.hpp \
		src/TRANSFER/Project.hpp \
		src/DAO/DAOTask.hpp \
		src/TRANSFER/Task.hpp \
		src/BUSINESS/Deadline.hpp \
		src/TRANSFER/Date.hpp \
		src/DAO/DAUtils.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TaskSwitcher.o src/BUSINESS/TaskSwitcher.cpp

DAOEmployee.o: src/DAO/DAOEmployee.cpp src/DAO/DAOEmployee.hpp \
		src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp \
		src/TRANSFER/Employee.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DAOEmployee.o src/DAO/DAOEmployee.cpp

DAOFactory.o: src/DAO/DAOFactory.cpp src/DAO/DAOFactory.hpp \
		src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DAOFactory.o src/DAO/DAOFactory.cpp

DAOInterface.o: src/DAO/DAOInterface.cpp src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DAOInterface.o src/DAO/DAOInterface.cpp

DAOProject.o: src/DAO/DAOProject.cpp src/DAO/DAOProject.hpp \
		src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp \
		src/TRANSFER/Project.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DAOProject.o src/DAO/DAOProject.cpp

DAOTask.o: src/DAO/DAOTask.cpp src/DAO/DAOTask.hpp \
		src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp \
		src/TRANSFER/Task.hpp \
		src/BUSINESS/Deadline.hpp \
		src/TRANSFER/Date.hpp \
		src/TRANSFER/Employee.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DAOTask.o src/DAO/DAOTask.cpp

QTTest01.o: src/TEST/QTTest01.cpp src/UI/MainWindow.h \
		src/UI/CommandAdapter.hpp \
		src/BUSINESS/Administrator.hpp \
		src/DAO/DAO.hpp \
		src/DAO/DAOFactory.hpp \
		src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp \
		src/DAO/DAOEmployee.hpp \
		src/TRANSFER/Employee.hpp \
		src/DAO/DAOProject.hpp \
		src/TRANSFER/Project.hpp \
		src/DAO/DAOTask.hpp \
		src/TRANSFER/Task.hpp \
		src/BUSINESS/Deadline.hpp \
		src/TRANSFER/Date.hpp \
		src/DAO/DAUtils.cpp \
		src/BUSINESS/ElementFactory.hpp \
		src/BUSINESS/TaskSwitcher.hpp \
		src/BUSINESS/ElementDropper.hpp \
		src/BUSINESS/TaskLister.hpp \
		src/BUSINESS/ElementLister.hpp \
		src/BUSINESS/EmployeeLister.hpp \
		src/BUSINESS/EmployeeFactory.hpp \
		src/BUSINESS/TaskFactory.hpp \
		src/BUSINESS/ProjectFactory.hpp \
		src/UI/ActionHandler.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QTTest01.o src/TEST/QTTest01.cpp

Date.o: src/TRANSFER/Date.cpp src/TRANSFER/Date.hpp \
		src/TRANSFER/Object.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Date.o src/TRANSFER/Date.cpp

Employee.o: src/TRANSFER/Employee.cpp src/TRANSFER/Employee.hpp \
		src/TRANSFER/Object.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Employee.o src/TRANSFER/Employee.cpp

Project.o: src/TRANSFER/Project.cpp src/TRANSFER/Project.hpp \
		src/TRANSFER/Object.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Project.o src/TRANSFER/Project.cpp

Task.o: src/TRANSFER/Task.cpp src/TRANSFER/Task.hpp \
		src/TRANSFER/Object.hpp \
		src/BUSINESS/Deadline.hpp \
		src/TRANSFER/Date.hpp \
		src/TRANSFER/Employee.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Task.o src/TRANSFER/Task.cpp

ActionHandler.o: src/UI/ActionHandler.cpp src/UI/ActionHandler.hpp \
		src/UI/CommandAdapter.hpp \
		src/BUSINESS/Administrator.hpp \
		src/DAO/DAO.hpp \
		src/DAO/DAOFactory.hpp \
		src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp \
		src/DAO/DAOEmployee.hpp \
		src/TRANSFER/Employee.hpp \
		src/DAO/DAOProject.hpp \
		src/TRANSFER/Project.hpp \
		src/DAO/DAOTask.hpp \
		src/TRANSFER/Task.hpp \
		src/BUSINESS/Deadline.hpp \
		src/TRANSFER/Date.hpp \
		src/DAO/DAUtils.cpp \
		src/BUSINESS/ElementFactory.hpp \
		src/BUSINESS/TaskSwitcher.hpp \
		src/BUSINESS/ElementDropper.hpp \
		src/BUSINESS/TaskLister.hpp \
		src/BUSINESS/ElementLister.hpp \
		src/BUSINESS/EmployeeLister.hpp \
		src/BUSINESS/EmployeeFactory.hpp \
		src/BUSINESS/TaskFactory.hpp \
		src/BUSINESS/ProjectFactory.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ActionHandler.o src/UI/ActionHandler.cpp

CommandAdapter.o: src/UI/CommandAdapter.cpp src/UI/CommandAdapter.hpp \
		src/BUSINESS/Administrator.hpp \
		src/DAO/DAO.hpp \
		src/DAO/DAOFactory.hpp \
		src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp \
		src/DAO/DAOEmployee.hpp \
		src/TRANSFER/Employee.hpp \
		src/DAO/DAOProject.hpp \
		src/TRANSFER/Project.hpp \
		src/DAO/DAOTask.hpp \
		src/TRANSFER/Task.hpp \
		src/BUSINESS/Deadline.hpp \
		src/TRANSFER/Date.hpp \
		src/DAO/DAUtils.cpp \
		src/BUSINESS/ElementFactory.hpp \
		src/BUSINESS/TaskSwitcher.hpp \
		src/BUSINESS/ElementDropper.hpp \
		src/BUSINESS/TaskLister.hpp \
		src/BUSINESS/ElementLister.hpp \
		src/BUSINESS/EmployeeLister.hpp \
		src/BUSINESS/EmployeeFactory.hpp \
		src/BUSINESS/TaskFactory.hpp \
		src/BUSINESS/ProjectFactory.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CommandAdapter.o src/UI/CommandAdapter.cpp

MainWindow.o: src/UI/MainWindow.cpp src/UI/MainWindow.h \
		src/UI/CommandAdapter.hpp \
		src/BUSINESS/Administrator.hpp \
		src/DAO/DAO.hpp \
		src/DAO/DAOFactory.hpp \
		src/DAO/DAOInterface.hpp \
		src/TRANSFER/Object.hpp \
		src/DAO/Query.hpp \
		src/DAO/DAOEmployee.hpp \
		src/TRANSFER/Employee.hpp \
		src/DAO/DAOProject.hpp \
		src/TRANSFER/Project.hpp \
		src/DAO/DAOTask.hpp \
		src/TRANSFER/Task.hpp \
		src/BUSINESS/Deadline.hpp \
		src/TRANSFER/Date.hpp \
		src/DAO/DAUtils.cpp \
		src/BUSINESS/ElementFactory.hpp \
		src/BUSINESS/TaskSwitcher.hpp \
		src/BUSINESS/ElementDropper.hpp \
		src/BUSINESS/TaskLister.hpp \
		src/BUSINESS/ElementLister.hpp \
		src/BUSINESS/EmployeeLister.hpp \
		src/BUSINESS/EmployeeFactory.hpp \
		src/BUSINESS/TaskFactory.hpp \
		src/BUSINESS/ProjectFactory.hpp \
		src/UI/ActionHandler.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o src/UI/MainWindow.cpp

qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_application.o qrc_application.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

